### ISSUE TITLE
Needs a contribution guide

### ISSUE THREAD

**Issue by adriel3005** [manoyes/subtend#1]
Project needs proper contribution guide. This will help keep a **clean repo** and have **consistent contributions** from other collaborators.

**Comment by adriel3005** [comment]
@manoyes Please revise the initial contributing guide created. It will need some updating as we create the relevant templates and as a Regex format is created to be enforced.

**Comment by manoyes** [comment]
@adriel3005 This looks really good. A couple things I would modify:

- For the first line in the commit message, use a capital first letter, and no punctuation
- Need to author the regex and write a pre-receive hook I can host to check for style
- We should set up issue description and pull request templates that include prompts for information request in the contribution guide. You can use HTML comments (`<!-- comment -->`) to help with this

**Comment by manoyes** [comment]
I finalized the Contribution guide. I added bug and issue templates and removed references to Regex because GitHub does not support them out of the box.
